version: '2'
 
services:
  app:
    build:
      context:  .
      dockerfile: Dockerfile
    expose:
      - "5000"
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    links:
      - app
